version: "3.9"

services:
  app:
    build: .
    ports:
      - "8503:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_ENABLEXSRFPROTECTION=false
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
